version: '3.8'

services:
  app:
    build: .
    image: python-devsecops-jenkins_app:latest
    container_name: flask-devsecops-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge